name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Auth to npm registry
        run: echo "TODO Implement npm registry authentication"

  audit_lint_prettier:
    runs-on: ubuntu-latest
    needs: auth
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Audit
        run: echo "TODO Implement npm audit"

      - name: Lint
        run: echo "TODO Implement linting"

      - name: Prettier
        run: echo "TODO Implement prettier check"

  build:
    runs-on: ubuntu-latest
    needs: audit_lint_prettier
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Copy .env.tpl to .env (frontend)
        run: cp frontend/.env.tpl frontend/.env

      - name: Install backend dependencies
        run: cd backend && npm ci

      - name: Install frontend dependencies
        run: cd frontend && npm ci

      - name: Build backend
        run: cd backend && npm run build

      - name: Build frontend
        run: cd frontend && npm run build

  test_unit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Copy .env.tpl to .env (frontend)
        run: cp frontend/.env.tpl frontend/.env

      - name: Install backend dependencies
        run: cd backend && npm ci

      - name: Install frontend dependencies
        run: cd frontend && npm ci

      - name: Backend unit tests
        run: cd backend && npm run test:unit

      - name: Frontend unit tests
        run: cd frontend && npm run test:unit

  test_e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Copy .env.tpl to .env (frontend)
        run: cp frontend/.env.tpl frontend/.env

      - name: Install backend dependencies
        run: cd backend && npm ci

      - name: Install frontend dependencies
        run: cd frontend && npm ci

      - name: Backend e2e tests
        run: cd backend && npm run test:e2e

      - name: Start backend
        run: |
          cd backend
          npm run build
          nohup npm run start &

      - name: Start frontend
        run: |
          cd frontend
          npm run build
          nohup npm run start &

      - name: Wait for backend to be ready
        run: |
          n=0
          until [ $n -ge 20 ]
          do
            nc -z localhost 3001 && break
            n=$((n+1))
            sleep 2
          done

      - name: Wait for frontend to be ready
        run: |
          n=0
          until [ $n -ge 20 ]
          do
            nc -z localhost 3000 && break
            n=$((n+1))
            sleep 2
          done

      - name: Frontend e2e tests
        run: |
          cd frontend
          npx playwright install --with-deps
          npm run test:e2e

  coverage:
    runs-on: ubuntu-latest
    needs: [test_unit, test_e2e]
    steps:
      - name: Coverage
        run: echo "TODO coverage report"

  deploy:
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - name: Deploy
        run: echo "TODO Implement deployment steps"
